"set utf-8 encode
set encoding=utf-8
" 去掉和vi的一致性
set nocompatible

silent function! OSX()
    return has('macunix')
endfunction


call plug#begin('~/.vim/Bundle')
" NERD tree
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'

" solarized
Plug 'altercation/vim-colors-solarized'

" lightline
Plug 'itchyny/lightline.vim'

" fzf for Mac OS
if OSX()
    Plug '/usr/local/opt/fzf'
    Plug 'junegunn/fzf.vim'
endif

"markdown
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'suan/vim-instant-markdown'

" ALE
Plug 'w0rp/ale'

call plug#end()

"set background for solarized
syntax enable
syntax on

if isdirectory(expand("~/.vim/Bundle/vim-colors-solarized"))
    set background=dark
    colorscheme solarized
    let g:solarized_termcolors=256
    let g:solarize_termtrans=1
    let g:solarize_constrast="normal"
    let g:solarize_visibility="normal"
endif

" set tab
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

"set backspace
set backspace=indent,eol,start
" 显示标尺
set ruler
" 显示行号
set number
" 显示当前行
set cursorline

"set syntax on and enable
filetype plugin indent on

" 搜索字符高亮
set hlsearch
set incsearch
" 忽略大小写
set ignorecase
" 定义tab的栏，显示所有可执行的命令
set wildmenu
set wildmode=longest:list,full
" 去除备份文件
set nobackup

" set cc line for 80
set cc=80

set nowrap
set autoindent
set cindent
" 显示括号匹配
set showmatch
set showcmd

" vimrc files
for s:path in split(glob('~/.vim/vimrc/*.vim'), "\n")
  exe 'source ' . s:path
endfor
